<?php 

/**
 * @author Kashyap Team
 * @copyright Copyright (c) 2018 Kashyap (softwarekashyap@gmail.com)
 * @package Kashyap_Nextpre
*/

$_product = $block->getProduct();

$prev_product = $block->getPrevProduct($_product);
$next_product = $block->getNextProduct($_product);
$enable = $block->getConfigure();
?>
<?php if($enable && ($prev_product || $next_product)): ?>
    <div class="product-next-prev">
        <?php if($next_product): ?>
            <a class="product-next" title="Next" href="<?php echo $next_product->getProductUrl(); ?>"><span>></span></a>
        <?php endif; ?>
        <?php if($prev_product): ?>
            <a class="product-prev" title="Previous" href="<?php echo $prev_product->getProductUrl(); ?>"><span><</span></a>
        <?php endif; ?>
    </div> 
<?php endif; ?>
